services:
  accountsdb:
    container_name: accountsdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "accountsdb"
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    container_name: loansdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "loansdb"
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    container_name: cardsdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "cardsdb"
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "cmghuy/configserver:s9"
    container_name: configserver-ms
    build:
      context: "../../configserver"
      dockerfile: "Dockerfile"
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "cmghuy/eurekaserver:s9"
    container_name: eurekaserver-ms
    build:
      context: "../../eurekaserver"
      dockerfile: "Dockerfile"
    ports:
      - "8070:8070"
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  accounts:
    image: "cmghuy/accounts:s9"
    container_name: accounts-ms
    build:
      context: "../../accounts"
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config
    depends_on:
      accountsdb:
        condition: service_healthy

  loans:
    image: "cmghuy/loans:s9"
    container_name: loans-ms
    build:
      context: "../../loans"
      dockerfile: "Dockerfile"
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config
    depends_on:
      loansdb:
        condition: service_healthy

  cards:
    image: "cmghuy/cards:s9"
    container_name: cards-ms
    build:
      context: "../../cards"
      dockerfile: "Dockerfile"
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config
    depends_on:
      cardsdb:
        condition: service_healthy

networks:
  cmghuy:
    driver: "bridge"
